Rename from strategies to intents
brinktrade/brink-types pull request #27
Opened 2023-09-27 14:48 UTC by MatiasOS

2023-10-04 01:47 UTC, mikec requested changes
small change then this is ready to go!

2023-10-04 01:47 UTC, mikec commented on src/Types.ts
> +export type DeclarationIntentArgs = {
anything that was "order" should be "intent" so this should be `IntentArgs`

2023-10-04 01:47 UTC, mikec commented on src/Types.ts
> +export type DeclarationIntentJSON = {
should be `IntentJSON`

2023-10-04 02:46 UTC, mikec commented on src/Types.ts
>    expiryBlock?: BigIntish
the DSL args can be named differently so they don't conflict. Also it looks like they're named at the wrong levels:

`IntentArgs` would be:

```
export type DeclarationDefinitionArgs = {
  intents: IntentSegmentArgs[]
  replay?: IntentReplay
  expiryBlock?: BigIntish
}

and `IntentSegmentArgs` would be:

```
export type IntentDefinitionArgs = {
  replay?: IntentReplay
  expiryBlock?: BigIntish
  conditions?: ConditionArgs[]
  actions: ActionArgs[]
}
```

2023-10-04 09:37 UTC, phanpak approved these changes

2023-10-05 17:32 UTC, mikec approved these changes

2023-10-05 19:50 UTC, merged