Fix marketSwapAction
brinktrade/brink-types pull request #29
Opened 2023-10-05 14:41 UTC by phanpak

2023-10-05 15:23 UTC, phanpak commented on src/Types.ts
> -  feeMinTokenOut?: BigIntish
i removed this one as i didn't see it in the docs.

2023-10-05 15:25 UTC, mikec requested changes

2023-10-05 15:25 UTC, mikec commented on src/Types.ts
> +  feePercent: number
this maps to the primitive fn endpoint, so this should be kept as BigIntish

2023-10-06 14:03 UTC, mikec approved these changes

2023-10-06 14:03 UTC, merged